apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone-app
          image: jaydengle/capstone-app:1.0
          ports:
            - containerPort: 3000
